# Generated by Django 2.2.5 on 2022-01-26 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kakaoproject', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClimateMessage',
        ),
    ]
