# Generated by Django 2.2.5 on 2022-01-23 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('tmp', models.TextField(primary_key=True, serialize=False)),
                ('pop', models.IntegerField(default=0)),
                ('pty', models.TextField()),
                ('reh', models.IntegerField(default=0)),
                ('sky', models.TextField()),
                ('wsd', models.IntegerField(default=0)),
            ],
        ),
    ]
